export interface CountryCode {
  code: string; // dial code e.g. "+63"
  iso: string; // ISO 3166-1 alpha-2 e.g. "PH"
  label: string; // country name
}

/** Full list of countries ordered alphabetically by label, Philippines first. */
export const COUNTRY_CODES: CountryCode[] = [
  { code: "+63", iso: "PH", label: "Philippines" },
  { code: "+93", iso: "AF", label: "Afghanistan" },
  { code: "+355", iso: "AL", label: "Albania" },
  { code: "+213", iso: "DZ", label: "Algeria" },
  { code: "+1", iso: "AS", label: "American Samoa" },
  { code: "+376", iso: "AD", label: "Andorra" },
  { code: "+244", iso: "AO", label: "Angola" },
  { code: "+1", iso: "AI", label: "Anguilla" },
  { code: "+672", iso: "AQ", label: "Antarctica" },
  { code: "+1", iso: "AG", label: "Antigua and Barbuda" },
  { code: "+54", iso: "AR", label: "Argentina" },
  { code: "+374", iso: "AM", label: "Armenia" },
  { code: "+297", iso: "AW", label: "Aruba" },
  { code: "+61", iso: "AU", label: "Australia" },
  { code: "+43", iso: "AT", label: "Austria" },
  { code: "+994", iso: "AZ", label: "Azerbaijan" },
  { code: "+1", iso: "BS", label: "Bahamas" },
  { code: "+973", iso: "BH", label: "Bahrain" },
  { code: "+880", iso: "BD", label: "Bangladesh" },
  { code: "+1", iso: "BB", label: "Barbados" },
  { code: "+375", iso: "BY", label: "Belarus" },
  { code: "+32", iso: "BE", label: "Belgium" },
  { code: "+501", iso: "BZ", label: "Belize" },
  { code: "+229", iso: "BJ", label: "Benin" },
  { code: "+1", iso: "BM", label: "Bermuda" },
  { code: "+975", iso: "BT", label: "Bhutan" },
  { code: "+591", iso: "BO", label: "Bolivia" },
  { code: "+387", iso: "BA", label: "Bosnia and Herzegovina" },
  { code: "+267", iso: "BW", label: "Botswana" },
  { code: "+55", iso: "BR", label: "Brazil" },
  { code: "+246", iso: "IO", label: "British Indian Ocean Territory" },
  { code: "+1", iso: "VG", label: "British Virgin Islands" },
  { code: "+673", iso: "BN", label: "Brunei" },
  { code: "+359", iso: "BG", label: "Bulgaria" },
  { code: "+226", iso: "BF", label: "Burkina Faso" },
  { code: "+257", iso: "BI", label: "Burundi" },
  { code: "+855", iso: "KH", label: "Cambodia" },
  { code: "+237", iso: "CM", label: "Cameroon" },
  { code: "+1", iso: "CA", label: "Canada" },
  { code: "+238", iso: "CV", label: "Cape Verde" },
  { code: "+1", iso: "KY", label: "Cayman Islands" },
  { code: "+236", iso: "CF", label: "Central African Republic" },
  { code: "+235", iso: "TD", label: "Chad" },
  { code: "+56", iso: "CL", label: "Chile" },
  { code: "+86", iso: "CN", label: "China" },
  { code: "+61", iso: "CX", label: "Christmas Island" },
  { code: "+61", iso: "CC", label: "Cocos Islands" },
  { code: "+57", iso: "CO", label: "Colombia" },
  { code: "+269", iso: "KM", label: "Comoros" },
  { code: "+243", iso: "CD", label: "Congo (DRC)" },
  { code: "+242", iso: "CG", label: "Congo (Republic)" },
  { code: "+682", iso: "CK", label: "Cook Islands" },
  { code: "+506", iso: "CR", label: "Costa Rica" },
  { code: "+385", iso: "HR", label: "Croatia" },
  { code: "+53", iso: "CU", label: "Cuba" },
  { code: "+599", iso: "CW", label: "Curaçao" },
  { code: "+357", iso: "CY", label: "Cyprus" },
  { code: "+420", iso: "CZ", label: "Czech Republic" },
  { code: "+45", iso: "DK", label: "Denmark" },
  { code: "+253", iso: "DJ", label: "Djibouti" },
  { code: "+1", iso: "DM", label: "Dominica" },
  { code: "+1", iso: "DO", label: "Dominican Republic" },
  { code: "+670", iso: "TL", label: "East Timor" },
  { code: "+593", iso: "EC", label: "Ecuador" },
  { code: "+20", iso: "EG", label: "Egypt" },
  { code: "+503", iso: "SV", label: "El Salvador" },
  { code: "+240", iso: "GQ", label: "Equatorial Guinea" },
  { code: "+291", iso: "ER", label: "Eritrea" },
  { code: "+372", iso: "EE", label: "Estonia" },
  { code: "+268", iso: "SZ", label: "Eswatini" },
  { code: "+251", iso: "ET", label: "Ethiopia" },
  { code: "+500", iso: "FK", label: "Falkland Islands" },
  { code: "+298", iso: "FO", label: "Faroe Islands" },
  { code: "+679", iso: "FJ", label: "Fiji" },
  { code: "+358", iso: "FI", label: "Finland" },
  { code: "+33", iso: "FR", label: "France" },
  { code: "+594", iso: "GF", label: "French Guiana" },
  { code: "+689", iso: "PF", label: "French Polynesia" },
  { code: "+241", iso: "GA", label: "Gabon" },
  { code: "+220", iso: "GM", label: "Gambia" },
  { code: "+995", iso: "GE", label: "Georgia" },
  { code: "+49", iso: "DE", label: "Germany" },
  { code: "+233", iso: "GH", label: "Ghana" },
  { code: "+350", iso: "GI", label: "Gibraltar" },
  { code: "+30", iso: "GR", label: "Greece" },
  { code: "+299", iso: "GL", label: "Greenland" },
  { code: "+1", iso: "GD", label: "Grenada" },
  { code: "+590", iso: "GP", label: "Guadeloupe" },
  { code: "+1", iso: "GU", label: "Guam" },
  { code: "+502", iso: "GT", label: "Guatemala" },
  { code: "+44", iso: "GG", label: "Guernsey" },
  { code: "+224", iso: "GN", label: "Guinea" },
  { code: "+245", iso: "GW", label: "Guinea-Bissau" },
  { code: "+592", iso: "GY", label: "Guyana" },
  { code: "+509", iso: "HT", label: "Haiti" },
  { code: "+504", iso: "HN", label: "Honduras" },
  { code: "+852", iso: "HK", label: "Hong Kong" },
  { code: "+36", iso: "HU", label: "Hungary" },
  { code: "+354", iso: "IS", label: "Iceland" },
  { code: "+91", iso: "IN", label: "India" },
  { code: "+62", iso: "ID", label: "Indonesia" },
  { code: "+98", iso: "IR", label: "Iran" },
  { code: "+964", iso: "IQ", label: "Iraq" },
  { code: "+353", iso: "IE", label: "Ireland" },
  { code: "+44", iso: "IM", label: "Isle of Man" },
  { code: "+972", iso: "IL", label: "Israel" },
  { code: "+39", iso: "IT", label: "Italy" },
  { code: "+225", iso: "CI", label: "Ivory Coast" },
  { code: "+1", iso: "JM", label: "Jamaica" },
  { code: "+81", iso: "JP", label: "Japan" },
  { code: "+44", iso: "JE", label: "Jersey" },
  { code: "+962", iso: "JO", label: "Jordan" },
  { code: "+7", iso: "KZ", label: "Kazakhstan" },
  { code: "+254", iso: "KE", label: "Kenya" },
  { code: "+686", iso: "KI", label: "Kiribati" },
  { code: "+383", iso: "XK", label: "Kosovo" },
  { code: "+965", iso: "KW", label: "Kuwait" },
  { code: "+996", iso: "KG", label: "Kyrgyzstan" },
  { code: "+856", iso: "LA", label: "Laos" },
  { code: "+371", iso: "LV", label: "Latvia" },
  { code: "+961", iso: "LB", label: "Lebanon" },
  { code: "+266", iso: "LS", label: "Lesotho" },
  { code: "+231", iso: "LR", label: "Liberia" },
  { code: "+218", iso: "LY", label: "Libya" },
  { code: "+423", iso: "LI", label: "Liechtenstein" },
  { code: "+370", iso: "LT", label: "Lithuania" },
  { code: "+352", iso: "LU", label: "Luxembourg" },
  { code: "+853", iso: "MO", label: "Macao" },
  { code: "+389", iso: "MK", label: "North Macedonia" },
  { code: "+261", iso: "MG", label: "Madagascar" },
  { code: "+265", iso: "MW", label: "Malawi" },
  { code: "+60", iso: "MY", label: "Malaysia" },
  { code: "+960", iso: "MV", label: "Maldives" },
  { code: "+223", iso: "ML", label: "Mali" },
  { code: "+356", iso: "MT", label: "Malta" },
  { code: "+692", iso: "MH", label: "Marshall Islands" },
  { code: "+596", iso: "MQ", label: "Martinique" },
  { code: "+222", iso: "MR", label: "Mauritania" },
  { code: "+230", iso: "MU", label: "Mauritius" },
  { code: "+262", iso: "YT", label: "Mayotte" },
  { code: "+52", iso: "MX", label: "Mexico" },
  { code: "+691", iso: "FM", label: "Micronesia" },
  { code: "+373", iso: "MD", label: "Moldova" },
  { code: "+377", iso: "MC", label: "Monaco" },
  { code: "+976", iso: "MN", label: "Mongolia" },
  { code: "+382", iso: "ME", label: "Montenegro" },
  { code: "+1", iso: "MS", label: "Montserrat" },
  { code: "+212", iso: "MA", label: "Morocco" },
  { code: "+258", iso: "MZ", label: "Mozambique" },
  { code: "+95", iso: "MM", label: "Myanmar" },
  { code: "+264", iso: "NA", label: "Namibia" },
  { code: "+674", iso: "NR", label: "Nauru" },
  { code: "+977", iso: "NP", label: "Nepal" },
  { code: "+31", iso: "NL", label: "Netherlands" },
  { code: "+687", iso: "NC", label: "New Caledonia" },
  { code: "+64", iso: "NZ", label: "New Zealand" },
  { code: "+505", iso: "NI", label: "Nicaragua" },
  { code: "+227", iso: "NE", label: "Niger" },
  { code: "+234", iso: "NG", label: "Nigeria" },
  { code: "+683", iso: "NU", label: "Niue" },
  { code: "+672", iso: "NF", label: "Norfolk Island" },
  { code: "+850", iso: "KP", label: "North Korea" },
  { code: "+1", iso: "MP", label: "Northern Mariana Islands" },
  { code: "+47", iso: "NO", label: "Norway" },
  { code: "+968", iso: "OM", label: "Oman" },
  { code: "+92", iso: "PK", label: "Pakistan" },
  { code: "+680", iso: "PW", label: "Palau" },
  { code: "+970", iso: "PS", label: "Palestine" },
  { code: "+507", iso: "PA", label: "Panama" },
  { code: "+675", iso: "PG", label: "Papua New Guinea" },
  { code: "+595", iso: "PY", label: "Paraguay" },
  { code: "+51", iso: "PE", label: "Peru" },
  { code: "+64", iso: "PN", label: "Pitcairn Islands" },
  { code: "+48", iso: "PL", label: "Poland" },
  { code: "+351", iso: "PT", label: "Portugal" },
  { code: "+1", iso: "PR", label: "Puerto Rico" },
  { code: "+974", iso: "QA", label: "Qatar" },
  { code: "+262", iso: "RE", label: "Réunion" },
  { code: "+40", iso: "RO", label: "Romania" },
  { code: "+7", iso: "RU", label: "Russia" },
  { code: "+250", iso: "RW", label: "Rwanda" },
  { code: "+290", iso: "SH", label: "Saint Helena" },
  { code: "+1", iso: "KN", label: "Saint Kitts and Nevis" },
  { code: "+1", iso: "LC", label: "Saint Lucia" },
  { code: "+508", iso: "PM", label: "Saint Pierre and Miquelon" },
  { code: "+1", iso: "VC", label: "Saint Vincent and the Grenadines" },
  { code: "+685", iso: "WS", label: "Samoa" },
  { code: "+378", iso: "SM", label: "San Marino" },
  { code: "+239", iso: "ST", label: "São Tomé and Príncipe" },
  { code: "+966", iso: "SA", label: "Saudi Arabia" },
  { code: "+221", iso: "SN", label: "Senegal" },
  { code: "+381", iso: "RS", label: "Serbia" },
  { code: "+248", iso: "SC", label: "Seychelles" },
  { code: "+232", iso: "SL", label: "Sierra Leone" },
  { code: "+65", iso: "SG", label: "Singapore" },
  { code: "+1", iso: "SX", label: "Sint Maarten" },
  { code: "+421", iso: "SK", label: "Slovakia" },
  { code: "+386", iso: "SI", label: "Slovenia" },
  { code: "+677", iso: "SB", label: "Solomon Islands" },
  { code: "+252", iso: "SO", label: "Somalia" },
  { code: "+27", iso: "ZA", label: "South Africa" },
  { code: "+82", iso: "KR", label: "South Korea" },
  { code: "+211", iso: "SS", label: "South Sudan" },
  { code: "+34", iso: "ES", label: "Spain" },
  { code: "+94", iso: "LK", label: "Sri Lanka" },
  { code: "+249", iso: "SD", label: "Sudan" },
  { code: "+597", iso: "SR", label: "Suriname" },
  { code: "+47", iso: "SJ", label: "Svalbard and Jan Mayen" },
  { code: "+46", iso: "SE", label: "Sweden" },
  { code: "+41", iso: "CH", label: "Switzerland" },
  { code: "+963", iso: "SY", label: "Syria" },
  { code: "+886", iso: "TW", label: "Taiwan" },
  { code: "+992", iso: "TJ", label: "Tajikistan" },
  { code: "+255", iso: "TZ", label: "Tanzania" },
  { code: "+66", iso: "TH", label: "Thailand" },
  { code: "+228", iso: "TG", label: "Togo" },
  { code: "+690", iso: "TK", label: "Tokelau" },
  { code: "+676", iso: "TO", label: "Tonga" },
  { code: "+1", iso: "TT", label: "Trinidad and Tobago" },
  { code: "+216", iso: "TN", label: "Tunisia" },
  { code: "+90", iso: "TR", label: "Turkey" },
  { code: "+993", iso: "TM", label: "Turkmenistan" },
  { code: "+1", iso: "TC", label: "Turks and Caicos Islands" },
  { code: "+688", iso: "TV", label: "Tuvalu" },
  { code: "+1", iso: "VI", label: "U.S. Virgin Islands" },
  { code: "+256", iso: "UG", label: "Uganda" },
  { code: "+380", iso: "UA", label: "Ukraine" },
  { code: "+971", iso: "AE", label: "United Arab Emirates" },
  { code: "+44", iso: "GB", label: "United Kingdom" },
  { code: "+1", iso: "US", label: "United States" },
  { code: "+598", iso: "UY", label: "Uruguay" },
  { code: "+998", iso: "UZ", label: "Uzbekistan" },
  { code: "+678", iso: "VU", label: "Vanuatu" },
  { code: "+379", iso: "VA", label: "Vatican City" },
  { code: "+58", iso: "VE", label: "Venezuela" },
  { code: "+84", iso: "VN", label: "Vietnam" },
  { code: "+681", iso: "WF", label: "Wallis and Futuna" },
  { code: "+212", iso: "EH", label: "Western Sahara" },
  { code: "+967", iso: "YE", label: "Yemen" },
  { code: "+260", iso: "ZM", label: "Zambia" },
  { code: "+263", iso: "ZW", label: "Zimbabwe" },
];
